
cores: 30
show-failed-logs: True
keep-going: True
keep-incomplete: True
rerun-incomplete: True
printshellcmds: False
keep-remote: True
use-conda: True
use-singularity: True

# default-remote-provider: "GS"
# default-remote-prefix: "orcestradata/gCSI-Pharmacoset_Snakemake"

# When running on Kubernetes
# jobs: 256       