
[project]
name = "gCSI-Pharmacoset_snakemake"


[tool.pixi.project]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
linux = "5.4.203"

[tool.pixi.dependencies]
singularity = ">=3.8.6,<3.9"
snakemake = "==7.32.4"

